### ISSUE TITLE
Is it possible to create MusicXmlDocument from parts and nodes ? 

### ISSUE THREAD

**Issue by DanielCardonaRojas** [de-men/music_xml#1]
First of all thank you for creating this package.

I'm currently working on a chord writing app and wanted to export to musicxml. From what I see MusicXmlDocument only has one exposed constructor which works by parsing a xml string.

I would like to map from my own data structures into parts and nodes from this library and do a conversion that way and create a MusicXmlDocument by creating all intermediate objects..

**Comment by thaihuynhxyz** [comment]
Yes, I allow public constructor at #2 please update `music_xml: ^1.0.4`
